
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
      sh "flutter clean"
      sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:697379356005:android:d9d041e760ba08b10d758c",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "mariioashraf1@gmail.com",
        release_notes: "First FastLane Firebase Distribution Stage Testing GitHub Actions"
      )
  end
end
