name: Android FastLane Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'  # Your Flutter version

      # Set up JDK 11 (required by Android)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build Android app using Fastlane
      - name: Firebase App Distribution
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}  # Secrets for Firebase token
        run: |
          bundle exec fastlane firebase_distribution
